name: greenshare
description: Share files conscientiously
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  dotted_border: ^2.1.0

  either_dart: ^1.0.0

  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  firebase_core: ^3.7.0
  firebase_database: ^11.1.5
  firebase_auth: ^5.3.2

  flutter_bloc: ^8.1.6

  equatable: ^2.0.5

  get_it: ^8.0.2
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  build_runner: ^2.4.11
  injectable_generator: ^2.6.2

  freezed: ^2.5.2
  json_serializable: ^6.8.0

  golden_toolkit: ^0.15.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  firebase_database_mocks: ^0.7.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-regular.ttf
        - asset: assets/fonts/Poppins-bold.ttf
          weight: 700

  generate: true
